# Generated by Django 5.0 on 2024-02-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'زن'), ('M', 'مرد')], max_length=1, verbose_name='جنسیت'),
        ),
    ]
